### ISSUE TITLE
Контроллер для invitation

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#143]
Есть модели приглашения в группу проекта #75, теперь нужно создать контроллер который позволит создать приглашение в проект пользотвалея и подтвердить приглашение, нужно
1) Создать контролле 
```
rails g controller invitations
```
2) У контроллера должно быть 2 метода create и agree
3) Доступ к методам контроллера должны иметь только авторизованные пользотвалеи, добавить в контроллер 
```
before_action :authenticate_user!
```
метод devise, который проверит что пользоваеть залогинен
4) Добавить в routes пути до нового контроллера
```
resources :projects do
  # тут другие пути
  resources :invitations, only: [create] do
    member do
        put :agree
      end
  end
end
```
Должны быть созданы пути /projects/:id/invitations и /projects/:id/invitations/:id, проверить можно выполнив в консоле команду
```
rails routes
```
5) Метод create получает project по id, получает user по email(уникальный идентификатор пользователя, проверка что пользователь существует и enable), и создает invitation (recipient: user)
6) Метод agree получает project по id, invitation по id и invitation.update(agree: true) и создает ProjectMember.create(project: project, user: current_user) - делать внутри транзакции https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html
7) Написать тесты

**Comment by sas2job** [comment]
Добавлено следующее
Хелпер **project_invitations_path** путь **/projects/:project_id/invitations(.:format)** экшен **invitations#agree**
Хелпер **agree_project_invitation_path** путь **/projects/:project_id/invitations/:id/agree(.:format)** экшен **invitations#create**
