### ISSUE TITLE
Создать api_tasks_controller

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#162]
Создать API контроллер для задачи, нужно:
1) Создать контроллер
```
rails g controller api/v1/tasks
```
2) Сделать наследником API::ApiController
3) Создать в контроллере метод show который получает id для tasks получает его из БД, сериализует и отдает клиенту
4) Метод должен перед вызовом проверять token_authenticate_user
5) Добавить нужный путь

**Comment by mrjoshua22** [comment]
ActiveRecord::RecordNotFound перехватывать будем? Например bad_request и сообщение об ошибке как в других апи контроллерах?

**Comment by vovs03** [comment]
👍🏻 : ответы от @XaoGao из чата

- так, для обычного контроллера у нас работает модуль `NotFoundHandler`

- ну вообще да, нам нужно переопределить `rescue_from ActiveRecord::RecordNotFound`, `with: :record_not_found` для `Api_controller`

---

**Comment by XaoGao** [comment]
@mrjoshua22 проверил, достаточно будет в ApiController переопредилть метод record_not_found(exception) - можно будет его открыть в разделе private
