### ISSUE TITLE
Add env file

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#2]
В будущем будет переход БД от sqlite на pg в docker, первым этапом будет созданием переменных окружения:
1) Добавить гем dotenv-rails(полная документация https://github.com/bkeepers/dotenv)
2) Добавить в .gitignor ".env" (чтобы в будущем данный файл не попал в github)
3) Создать .env.example файл в корне проекта с содержимым 
`DATABASE_USER=login for your DB
DATABASE_PASSWORD=password for your login
DATABASE_HOST= host where run DB like "127.0.0.1"
DATABASE_PORT= port where run DB like "5432"
`
4) У разработчика локально так же должен быть файл .env с реальными данными
5) Убедиться что приложение может корректно считывать данные с файла

**Comment by vovs03** [comment]
> 3. Создать .env.example файл в корне проекта с содержимым
>    `DATABASE_USER=login for your DB DATABASE_PASSWORD=password for your login DATABASE_HOST= host where run DB like "127.0.0.1" DATABASE_PORT= port where run DB like "5432" `

@XaoGao а как проверить, что эти тестовые данные из примера сработают? Или этот файл только пример? Понял, что только пример.
Тогда может сразу стоит заполнить ~~такими~~ этими данными файл `.env.development` ?

**Comment by XaoGao** [comment]
@vovs03 Пока пусть будет такая запись, следующим шагом будет поддержка pg в docker  и уже можно будет указать нормальные данные для локального развертывания, в рамках данной задачи оставим эту заглушку

**Comment by XaoGao** [comment]
>

**Comment by XaoGao** [comment]
> пункт 5 - @sas2job а как просиходит проверка в #3 ?

@vovs03  Можно вызывать в консоле например  ENV.fetch("DATABASE_PORT") и должны вернуться данные
