### ISSUE TITLE
Seeds

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#20]
Для первичного развертывания хорошо иметь заполненую БД, в rails есть команда `rails db:seed` которая выполнить руби код для заполнения таблицы данными
Нужно
1) Найти файл db/seeds.rb
2) Удалить содержимое файла
3) Добавить код для добавления пользователей, пусть логин будет простой и максимально повторяться, пароль должен быть password
`10.times do |i|
  User.create(
    first_name: Faker::Name.first_name,
    last_name: Faker::Name.last_name,
    email: "t#{i}@t.com",
    password: "password"
  )
end`
4) Добавить в файл  код для добавление проектов
`10.times do |i|
  Project.create(
    title: Faker::App.name,
    author: User.all.sample,
    short_title: "#{i}-p",
    status: Project.statuses[:active]
  )
end`
5) Код для добавление задач в проекты
`Project.all.each do |project|
  10.times do
    Task.create(
      title: Faker::App.name,
      description: Faker::Lorem.paragraph,
      status: 0,
      author: User.all.sample,
      project: project
    )
  end
end`
6) Код для добавление связи пользователя и проекта
`20.times do |i|
  ProjectMember.create(
    project: Project.all.sample,
    user: User.all.sample
  )
end`

**Comment by sas2job** [comment]
Сиды не работают тк один из полей user'a обязателен, а в сидах его нет.

**Comment by XaoGao** [comment]
Поле username для модели User, можно использовать метод Faker::Internet.username для заполнения
