### ISSUE TITLE
Добавить пагинацию для Projects#index

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#211]
Так как у пользователя может быть очень много проектов, то стоит разделить их отображение по страницам(в будущем будет infinity scroll), выполнить после #74, отображать по 10 проектов на странице. Так же для красивого отображения можно выполнить
```
rails g kaminari:views bootstrap4 -e slim
```

**Comment by sas2job** [comment]
`$ rails g kaminari:views bootstrap4 -e slim`
Пока не работает на ubuntu 22.04 
`.asdf/installs/ruby/2.7.0/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)`
