### ISSUE TITLE
Добавить jwt

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#25]
В будущем будет интеграция через api. Нужно будет продумать схему авторизации. Реализуем ее через Bearer token, нужно:
1) Добавить в gemfile gem 'jwt'
2) Запустить bundle install
3) В папке app/services файл  jwt_service.rb
4) В файле создать класс JwtService
5) Создать методы класса encode и decode
6) У метода класса encode входящие параметры payload (данные которые мы будем шифровать в виде хеша) и expired(время жизни токена) - опциональный параметр, default значение DateTime.now + 1.hour
7) У метода decode входящий параметр token - jwt который мы будем расшифровывать
8) Данные методы должны вызывать методы гема jwt (см. документацию https://github.com/jwt/ruby-jwt)
9) Написать тесты в spec/services/jwt_service_spec.rb на данные методы

**Comment by mrjoshua22** [comment]
В jwt есть несколько алгоритмов - NONE, HMAC, RSASSA and ECDSA. Использовать какой-либо из них или оставить NONE (unsigned token)?

**Comment by XaoGao** [comment]
@mrjoshua22 будем использовать стандартный алгоритм HMAC, так же секретный ключ можно сгенерировать через любой сервис, его стоит сохранить в Rails.application.credentials с названием "jwt_secret_key"

**Comment by mrjoshua22** [comment]
В методах я прописал Rails.application.credentials.jwt_secret_key, но для добавления нужен же master.key?
И нужна ли обработка expired token для метода decode раз соответствующий параметр передается в encode?

**Comment by XaoGao** [comment]
В метод "decode" передается только токен, данный метод расшифрует данные в виде хеша и вернет его, параметр expired будет лежать в этом хеше и обработка(что делать если токен протух или нет) уже будет решать вызывающий объект
