### ISSUE TITLE
🤖 Add automate notification for Telegram-chat (new `issue`, `PR`)

### ISSUE THREAD

**Issue by vovs03** [XaoGao/Todoser#26]
# 🤖 Add automate notification for Telegram-chat 

> telegram_chat_users_Todoser can see:
- 📝 message about published new `issue`
-  📜 message about published new `PR`

@XaoGao можно я сделаю?

**Comment by XaoGao** [comment]
@vovs03 не совсем понятно как будет реалезовано, уже есть готовые чат боты? Если да, то можно реализовать

**Comment by XaoGao** [comment]
Подключен в группу телеграмме
