### ISSUE TITLE
Service-object

### ISSUE THREAD

**Issue by vovs03** [XaoGao/Todoser#27]
# Service-object

- [x] 1. Подтянуть все свежие изменения  по ветке master
- [x] 2. Создать новую ветку service-object
- [x] 3. в папке services создать файл service.rb
- [x] 4. Создать в нем класс `Service`
- [ ] 5. Так как мы в сервисах всегда будем создавать результаты выполнения и они будут двух видов, то лучше создать в них сразу методы хелперы:
  - 1ый метод `success(data)` который просто создает Result.new(true,data,nil) и 
  -  второй метод `failure(error_message, data = nil)` (просто не всегда нужно будет передавать этот параметр) `Result.new(false, data, error_messages)`

# Status

🔵 @vovs03 in work

**Comment by XaoGao** [comment]
@vovs03 Создать в папке spec/service файл service_spec.rb и написать тесты на на методы success и failure

**Comment by XaoGao** [comment]
Тесты будут написаны в отдельном PR

**Comment by vovs03** [comment]
> @XaoGao  Тесты будут написаны в отдельном PR

я читал, что лучше в одном PR иметь код + тесты (сорри, что так долго делаю задачу.)

**Comment by vovs03** [comment]
# Переменная `data`

# Тест
![Screenshot 2022-06-07 at 15 55 24](https://user-images.githubusercontent.com/21124057/172385220-0f916fef-f1c9-43a8-8f11-e49a5844cc0e.jpg)

# Код

> `spec/services/service_spec.rb`
```ruby
require 'rails_helper'

RSpec.describe Service do
  describe "success" do
    it 'success is true' do
      service = Result.new(true, data, nil)
      expect(service.success).to be true
    end

    # xit 'success is false' do
    #   service = Result.new(true, data, nil)
    #   expect(service.success).to be false
    # end
  end

  describe "failure" do
    xit 'failure is true' do
      service = Result.new(false, data, error_messages)
      expect(service.failure).to be true
    end
  end
end
```

В моём понимании мы `data` берём из [`/app/services/result.rb`](https://github.com/XaoGao/Todoser/blob/master/app/services/result.rb)

**Comment by vovs03** [comment]
Значит я не так понял 5й пункт #27 таски

**Comment by vovs03** [comment]
Спеки добавил (но что-то внутри ощущение, что это чит)
