### ISSUE TITLE
Добавить комментари

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#29]
Создать новую модель Comment с полями 
t.text :body, default: "", null: false (сам комментарий )
t.references :user, references: :user, null: false, foreign_key: { to_table: :users } (кто оставил комментацрии)
t.references :commentable, polymorphic: true (полиморфная связь, так как комментарии можно будет оставлять к расзным сущностям таким как Проект, Задача и прочее)
t.datetime delete_at default: nil

Правила для модель: 
belongs_to :user, dependent: :destroy
belongs_to :commentable, polymorphic: true, dependent: :destroy

validates :body, presence: true, length: { maximum: 1000 }

**Comment by XaoGao** [comment]
@sas2job created_at и updated_at обязательные поля для при созздании новой записи в БД(первое значение updated_at при создании новой записи ровно created_at). В данном приложении мы будет реализовывать `soft delete`, мы не будет удалять запись из БД, а просто проставлять значение для delete_at. Таким образом все активные записи в БД будут с delete_at == nil, а удаленные delete_at != nil (в данном поле будет время когда запись была удалена). Так же была допущено ошибка при наименования поля нужно будет в новой таске пременовать поле в delete`d`_at у всех моделей

**Comment by sas2job** [comment]
Сделал локально миграцию и возник вопрос
`удаленные delete_at != nil (в данном поле будет время когда запись была удалена)`
Что такое время?
  t.datetime
  t.timestamp
  t.time
  t.date

**Comment by XaoGao** [comment]
@sas2job локально все ок, закрываю issue, PR идет в мастер
