### ISSUE TITLE
Добавить библиотеку для динамического оповещения пользователя

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#41]
Что бы динамический оповещать пользователя будем использовать npm библиотеку toastr https://www.npmjs.com/package/toastr, нужно
1) Запустить yarn add toastr
2) Добавить в application.js
`import toastr from 'toastr';

toastr.options = {
  "closeButton": true
};

global.toastr = toastr;`
3) В application.scss добавить @import 'toastr/build/toastr.min';

**Comment by vovs03** [comment]
Посмотрел [toasr/demo](https://codeseven.github.io/toastr/demo.html) - 😸 Прикольный чел этот `Inigo Montoya`
- [x] `|> Toasts`
