### ISSUE TITLE
Добавить в gitignore yarn.lock

### ISSUE THREAD

**Issue by RaptorialThing** [XaoGao/Todoser#48]
unable merge xaodao version with local bc git says: Неотслеживаемые файлы:
(используйте «git add <файл>…», чтобы добавить в то, что будет включено в коммит)

yarn.lock
My suggestion - add yarn.lock to .gitignore file

**Comment by XaoGao** [comment]
@RaptorialThing Описание задачи лучше развернуть: Если сколнировать файл и запустить команду yarn install то появиться yarn.lock файл, который отслеживает зависимости для npm пакетов, стоит добавить его в .gitinore  файл
