### ISSUE TITLE
Добавить указатель на конкретные тесты

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#53]
Добавить возможность запускать конкретные тесты, для этого нужно:
1) Указать настройки в файле spec_helper
`config.filter_run_when_matching :focus`
2) Проверить, для этого выбрать любой тест и передать параметром `:focus`
Например
RSpec.describe User, type: :model do
  describe ".full_name", **:focus** ...
Запустить тесты набрав в консоле rspec, должен будет выполниться тесты только из этого   describe

**Comment by sas2job** [comment]
Также можно использовать следующие указатели в блоке it:
it 'can do so and so', focus: true do
  # This is the only test that will run
end
или
fit 'can do so and so' do
  # This is the only test that will run
end
