### ISSUE TITLE
Добавить гем bullet

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#61]
Во время разработки можно пропустить ненжные обращения к БД(проблема называется N + 1) для того чтобы отловить данную проблему можно использовать гем bullet (https://github.com/flyerhzm/bullet), нужно:
1) Добавить **gem 'bullet'** В Gemfile в группу **development**
2) Установить гем. Выполнить команду в терминале **bundle install**
3) Запустить генератор, чтобы установить гем в rails **rails g bullet:install**
4) В файле **config/environments/development.rb**  добавить
```ruby
config.after_initialize do
    Bullet.enable        = true
    # Bullet.alert         = true
    Bullet.bullet_logger = true
    Bullet.console       = true
    Bullet.rails_logger  = true
    Bullet.add_footer    = true
  end
```

**Comment by vovs03** [comment]
@XaoGao После генерации `rails g bullet:install` ещё произошли изменения в файле:
-  `config/environments/test.rb`

их тоже надо включить?

**Comment by XaoGao** [comment]
@vovs03 да, эти изменения указыавают, что bullet будет работать и про прогоне теста
