### ISSUE TITLE
Добавить в модель User поле locale

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#67]
Сейчас сайт использует en язык по умолчанию, в будущем будет поддержка нескольких языков как первый шаг, нужно добавить в модель User новое string поле **locale**, которое по дефолту будет **en**, нужно
1) Создать новую миграцию rails g migration AddLocaleToUsers
2) В миграции указать
```ruby
def change
  add_column :users, :locale :string, default: "en", null: false
  User.all.each do |user|
    user.update(locale: "en")
  end
end
```
3) Запустить миграцию командой       
```
rails db:migrate
```
4) Добавить данное поле в **db/seeds.rb**
5) Добавить данное поле в **spec/factories/users.rb**
6) Добавить данное поле в комментарии черзе gem annotate, для этого запустить в терминале 
```
annotate --models
```

**Comment by XaoGao** [comment]
@kylaten повесил задачу на тебя, при разработке тебе не нужно будет фронт) будут вопросы пиши сюда

**Comment by kylaten** [comment]
@XaoGao "как первый шаг, нужно добавить в модель User новое string поле locale, которое по дефолту будет en, нужно..." - не очень понял про поле locale и запутало "как первый шаг" и потом 1 пункт после описания первого шага
