### ISSUE TITLE
Flash для Result

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#68]
В будущем бизнес логика будет перемещена из методов контроллера в service object и очень часто будет проверка
```ruby
result = Service.new.call
if result.success?
  flash[:notice] = result.data
else
  flash[:alert] = result.error_messages
end
```
Лучше сразу вынести это в отдельный метод и так как он будет во многих контроллерах его стоит добавить 
application_controller.rb
Метод можно назвать flash_service_result(result)
Написать тесты

**Comment by markcodexq** [comment]
А в application controller этот метод(flash_service_result) поместить в какой раздел? protected?

**Comment by XaoGao** [comment]
@markcodexq пусть будет публичным методом

**Comment by markcodexq** [comment]
Вынес метод, как понял его нужно тестировать в spec/components/flash?
