### ISSUE TITLE
Макет Homepage

### ISSUE THREAD

**Issue by vovs03** [XaoGao/Todoser#7]
# Макет Homepage

у меня в браузере пока что так...
![Homepage](https://user-images.githubusercontent.com/21124057/170236430-721f3b4b-00e2-45b0-8b31-f50a6c974ad3.jpg)

**Comment by XaoGao** [comment]
Нужно сделать  следующие шаги :  удалить папку node_modules -> rails webpacker:install -> yarn install -> yarn add popper.js@^1.16.1 -> bundle install -> rails server

**Comment by vovs03** [comment]
# Solution

1️⃣ `rm -rf node_modules`
2️⃣ `rails webpacker:install`
3️⃣  `yarn install`
4️⃣  `yarn add popper.js@1.16.1`
5️⃣  `bundle install`
6️⃣  `rails s`

**Comment by vovs03** [comment]
# Граф зависимостей

> `gem install ruby-graphviz`

- [x] to start: `bundle viz` 
- [x] смотреть при 500% -увеличении
 
![gem_graph](https://user-images.githubusercontent.com/21124057/171819291-e0ac7eb4-e0f6-46ee-b7c5-9f71d1d1c1b7.png)

# Gemfile.lock
- `mini_portile2 (2.7.1)`
- `nokogiri (1.13.1)`
    - `mini_portile2 (~> 2.7.0)`
    - `racc (~> 1.4)`

- [Changes Gemfile.lock](https://github.com/XaoGao/Todoser/pull/28/commits/9d821e0e20ab91ef1cd71bfb509384a7c249b63e)
